version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:${POST_DB_DATA}
    networks:
      back_net:
        aliases:
         - post_db
         - comment_db
      front_net:
        aliases:
         - post_db
         - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}
    networks:
      front_net:
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
        aliases:
         - post
      front_net:

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
        aliases:
         - comment
      front_net:

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      back_net:
      front_net:

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
      front_net:

  mongodb-exporter:
    image: percona/mongodb_exporter:0.36
    ports:
    - '9216:9216'
    - '27017:27017'
    depends_on:
      - post_db
    command:
    - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      back_net:
      front_net:


  blackbox-exporter:
    user: root
    image: quay.io/prometheus/blackbox-exporter:latest
    ports:
      - '9115:9115'
    networks:
      back_net:
      front_net:

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${BACK_SUBNET}
  front_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${FRONT_SUBNET}
