apiVersion: apps/v1
kind: Deployment
metadata: # Блок метаданных деплоя
  name: ui
  labels:
    app: reddit
    component: ui
spec: # Блок спецификации деплоя
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
  template: # Блок описания POD-ов
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
    spec:
      containers:
      - image: santikas/ui # Не забудьте подставить свой образ
        name: ui
        ports:
        - containerPort: 9292
        env:
        - name: ENV # Извлекаем значение из контекста запуска
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
