services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:${POST_DB_DATA}
    network-alias:
      - post_db
      - comment_db
    networks:
      - back_net
      - front_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    network-alias:
      - post
    networks:
      - back_net
      - front_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    network-alias:
      - comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${BACK_SUBNET}
  front_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${FRONT_SUBNET}
